// ================================================================
// TV-CHECKPROGRAMM — Real Channel Database
// EPG data source: epg.pw (free, no key required)
// API: https://epg.pw/api/epg.json?channel_id=ID&timezone=Europe/Moscow
// ================================================================

window.CHANNELS = [
  // ============ ФЕДЕРАЛЬНЫЕ ТВ (мультиплекс 1+2) ============
  {
    id: 1,            // epg.pw channel_id
    epgId: 'ChannelOne.ru',
    name: 'Первый канал',
    type: 'tv',
    cat: 'federal',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Pervyi_Kanal.svg/120px-Pervyi_Kanal.svg.png',
    color: '#1565C0',
    abbr: '1',
  },
  {
    id: 2,
    epgId: 'Russia1.ru',
    name: 'Россия 1',
    type: 'tv', cat: 'federal',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Russia-1.svg/120px-Russia-1.svg.png',
    color: '#C62828', abbr: 'Р1',
  },
  {
    id: 3,
    epgId: 'Match.ru',
    name: 'Матч ТВ',
    type: 'tv', cat: 'sport',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Match_TV_logo.svg/120px-Match_TV_logo.svg.png',
    color: '#E65100', abbr: '⚽',
  },
  {
    id: 4,
    epgId: 'NTV.ru',
    name: 'НТВ',
    type: 'tv', cat: 'federal',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/NTV_logo.svg/120px-NTV_logo.svg.png',
    color: '#00897B', abbr: 'НТВ',
  },
  {
    id: 5,
    epgId: '5Kanal.ru',
    name: 'Пятый канал',
    type: 'tv', cat: 'federal',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Pyaty_kanal_2022.png/120px-Pyaty_kanal_2022.png',
    color: '#6A1B9A', abbr: '5',
  },
  {
    id: 6,
    epgId: 'RussiaK.ru',
    name: 'Россия К',
    type: 'tv', cat: 'culture',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Rossiya_Kultura_logo_2010.svg/120px-Rossiya_Kultura_logo_2010.svg.png',
    color: '#2E7D32', abbr: 'РК',
  },
  {
    id: 7,
    epgId: 'Russia24.ru',
    name: 'Россия 24',
    type: 'tv', cat: 'news',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Rossiya_24_logo.svg/120px-Rossiya_24_logo.svg.png',
    color: '#0D47A1', abbr: 'Р24',
  },
  {
    id: 8,
    epgId: 'Karusel.ru',
    name: 'Карусель',
    type: 'tv', cat: 'kids',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Karusel_logo.svg/120px-Karusel_logo.svg.png',
    color: '#F9A825', abbr: '🎠',
  },
  {
    id: 9,
    epgId: 'OTR.ru',
    name: 'ОТР',
    type: 'tv', cat: 'federal',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/OTR_logo.svg/120px-OTR_logo.svg.png',
    color: '#37474F', abbr: 'ОТР',
  },
  {
    id: 10,
    epgId: 'TVCentr.ru',
    name: 'ТВ Центр',
    type: 'tv', cat: 'news',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/TV_Centre_logo.svg/120px-TV_Centre_logo.svg.png',
    color: '#1565C0', abbr: 'ТВЦ',
  },
  {
    id: 11,
    epgId: 'RENTV.ru',
    name: 'РЕН ТВ',
    type: 'tv', cat: 'federal',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Ren_TV_logo_%282015%29.svg/120px-Ren_TV_logo_%282015%29.svg.png',
    color: '#D81B60', abbr: 'РЕН',
  },
  {
    id: 12,
    epgId: 'TelekanalSpas.ru',
    name: 'Спас',
    type: 'tv', cat: 'culture',
    logo: '', color: '#795548', abbr: '✝',
  },
  {
    id: 13,
    epgId: 'STS.ru',
    name: 'СТС',
    type: 'tv', cat: 'entertainment',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/STS_channel.svg/120px-STS_channel.svg.png',
    color: '#F57C00', abbr: 'СТС',
  },
  {
    id: 14,
    epgId: 'Domashniy.ru',
    name: 'Домашний',
    type: 'tv', cat: 'entertainment',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Domashniy_logo.svg/120px-Domashniy_logo.svg.png',
    color: '#EC407A', abbr: '🏠',
  },
  {
    id: 15,
    epgId: 'TV3.ru',
    name: 'ТВ-3',
    type: 'tv', cat: 'entertainment',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/TV-3_Russia_2014_logo.svg/120px-TV-3_Russia_2014_logo.svg.png',
    color: '#7B1FA2', abbr: 'ТВ3',
  },
  {
    id: 16,
    epgId: 'Pyatnitsa.ru',
    name: 'Пятница!',
    type: 'tv', cat: 'entertainment',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Friday_Russia_logo.svg/120px-Friday_Russia_logo.svg.png',
    color: '#FF6F00', abbr: 'Пт!',
  },
  {
    id: 17,
    epgId: 'Zvezda.ru',
    name: 'Звезда',
    type: 'tv', cat: 'federal',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Zvezda_TV_logo.svg/120px-Zvezda_TV_logo.svg.png',
    color: '#1A237E', abbr: '⭐',
  },
  {
    id: 18,
    epgId: 'Mir.ru',
    name: 'МИР',
    type: 'tv', cat: 'federal',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Mir_logo.svg/120px-Mir_logo.svg.png',
    color: '#00695C', abbr: 'МИР',
  },
  {
    id: 19,
    epgId: 'TNT.ru',
    name: 'ТНТ',
    type: 'tv', cat: 'entertainment',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/TNT_Russia_2016_logo.svg/120px-TNT_Russia_2016_logo.svg.png',
    color: '#E53935', abbr: 'ТНТ',
  },
  {
    id: 20,
    epgId: 'MuzTV.ru',
    name: 'МУЗ-ТВ',
    type: 'tv', cat: 'music',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/MUZ-TV_logo_%282013%29.svg/120px-MUZ-TV_logo_%282013%29.svg.png',
    color: '#E91E63', abbr: '🎵',
  },
  {
    id: 21,
    epgId: 'Che.ru',
    name: 'ЧЕ!',
    type: 'tv', cat: 'entertainment',
    logo: '', color: '#FF5722', abbr: 'ЧЕ',
  },
  {
    id: 22,
    epgId: 'TNT4.ru',
    name: 'ТНТ 4',
    type: 'tv', cat: 'entertainment',
    logo: '', color: '#C62828', abbr: 'ТНТ4',
  },
  {
    id: 23,
    epgId: 'STSLove.ru',
    name: 'СТС Love',
    type: 'tv', cat: 'entertainment',
    logo: '', color: '#E91E63', abbr: '💕',
  },
  {
    id: 24,
    epgId: 'Disney.ru',
    name: 'Disney Channel',
    type: 'tv', cat: 'kids',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Disney_Channel_logo.svg/120px-Disney_Channel_logo.svg.png',
    color: '#1565C0', abbr: '✨',
  },
  {
    id: 25,
    epgId: 'Nickelodeon.ru',
    name: 'Nickelodeon',
    type: 'tv', cat: 'kids',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Nickelodeon_2009_logo.svg/120px-Nickelodeon_2009_logo.svg.png',
    color: '#FF5722', abbr: '🟠',
  },
  {
    id: 26,
    epgId: 'Mult.ru',
    name: 'Мульт',
    type: 'tv', cat: 'kids',
    logo: '', color: '#7E57C2', abbr: '🐱',
  },
  {
    id: 27,
    epgId: 'Eurosport1.ru',
    name: 'Eurosport 1',
    type: 'tv', cat: 'sport',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Eurosport_1_logo.svg/120px-Eurosport_1_logo.svg.png',
    color: '#1565C0', abbr: 'ES1',
  },
  {
    id: 28,
    epgId: 'Eurosport2.ru',
    name: 'Eurosport 2',
    type: 'tv', cat: 'sport',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Eurosport_2_logo.svg/120px-Eurosport_2_logo.svg.png',
    color: '#0D47A1', abbr: 'ES2',
  },
  {
    id: 29,
    epgId: 'MatchFootball1.ru',
    name: 'Матч! Футбол 1',
    type: 'tv', cat: 'sport',
    logo: '', color: '#2E7D32', abbr: 'МФ1',
  },
  {
    id: 30,
    epgId: 'MatchFootball2.ru',
    name: 'Матч! Футбол 2',
    type: 'tv', cat: 'sport',
    logo: '', color: '#1B5E20', abbr: 'МФ2',
  },
  {
    id: 31,
    epgId: 'MatchFootball3.ru',
    name: 'Матч! Футбол 3',
    type: 'tv', cat: 'sport',
    logo: '', color: '#33691E', abbr: 'МФ3',
  },
  {
    id: 32,
    epgId: 'RBK.ru',
    name: 'РБК ТВ',
    type: 'tv', cat: 'news',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/RBK_TV_logo.svg/120px-RBK_TV_logo.svg.png',
    color: '#B71C1C', abbr: 'РБК',
  },
  {
    id: 33,
    epgId: 'Moscow24.ru',
    name: 'Москва 24',
    type: 'tv', cat: 'news',
    logo: '', color: '#1565C0', abbr: 'М24',
  },
  {
    id: 34,
    epgId: 'Nauka.ru',
    name: 'Наука',
    type: 'tv', cat: 'doc',
    logo: '', color: '#0277BD', abbr: '🔬',
  },
  {
    id: 35,
    epgId: 'Bibigon.ru',
    name: 'Бибигон',
    type: 'tv', cat: 'kids',
    logo: '', color: '#F57F17', abbr: '🦒',
  },
  {
    id: 36,
    epgId: 'NashiFilmy.ru',
    name: 'Наши фильмы',
    type: 'tv', cat: 'movies',
    logo: '', color: '#BF360C', abbr: '🎬',
  },
  {
    id: 37,
    epgId: 'KinoHit.ru',
    name: 'Кино Хит',
    type: 'tv', cat: 'movies',
    logo: '', color: '#4A148C', abbr: '🎞',
  },
  {
    id: 38,
    epgId: 'TV1000.ru',
    name: 'TV 1000',
    type: 'tv', cat: 'movies',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/TV1000_logo.svg/120px-TV1000_logo.svg.png',
    color: '#880E4F', abbr: '🎥',
  },
  {
    id: 39,
    epgId: 'Kinopremiera.ru',
    name: 'Киноклуб',
    type: 'tv', cat: 'movies',
    logo: '', color: '#1A237E', abbr: '🎭',
  },
  {
    id: 40,
    epgId: 'NTV-Serial.ru',
    name: 'НТВ Сериал',
    type: 'tv', cat: 'movies',
    logo: '', color: '#004D40', abbr: 'НТВс',
  },
  {
    id: 41,
    epgId: 'Discovery.ru',
    name: 'Discovery Channel',
    type: 'tv', cat: 'doc',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Discovery_Channel_Russia_logo.svg/120px-Discovery_Channel_Russia_logo.svg.png',
    color: '#1565C0', abbr: '🔭',
  },
  {
    id: 42,
    epgId: 'NatGeo.ru',
    name: 'National Geographic',
    type: 'tv', cat: 'doc',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Natgeologo.svg/120px-Natgeologo.svg.png',
    color: '#F9A825', abbr: 'NG',
  },
  {
    id: 43,
    epgId: 'AnimalPlanet.ru',
    name: 'Animal Planet',
    type: 'tv', cat: 'doc',
    logo: '', color: '#2E7D32', abbr: '🐘',
  },
  {
    id: 44,
    epgId: 'HistoryChannel.ru',
    name: 'History Channel',
    type: 'tv', cat: 'doc',
    logo: '', color: '#37474F', abbr: '⚔',
  },
  {
    id: 45,
    epgId: 'DiscoveryScience.ru',
    name: 'Discovery Science',
    type: 'tv', cat: 'doc',
    logo: '', color: '#0277BD', abbr: 'DS',
  },
  {
    id: 46,
    epgId: 'CNN.ru',
    name: 'CNN',
    type: 'tv', cat: 'news',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/CNN.svg/120px-CNN.svg.png',
    color: '#CC0000', abbr: 'CNN',
  },
  {
    id: 47,
    epgId: 'BBCWorld.ru',
    name: 'BBC World News',
    type: 'tv', cat: 'news',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/BBC_World_News_2022_%28Alt%29.svg/120px-BBC_World_News_2022_%28Alt%29.svg.png',
    color: '#BB0000', abbr: 'BBC',
  },
  {
    id: 48,
    epgId: 'Euronews.ru',
    name: 'Euronews',
    type: 'tv', cat: 'news',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Euronews_2022.svg/120px-Euronews_2022.svg.png',
    color: '#003399', abbr: 'EN',
  },
  {
    id: 49,
    epgId: 'France24.ru',
    name: 'France 24',
    type: 'tv', cat: 'news',
    logo: '', color: '#003399', abbr: 'F24',
  },
  {
    id: 50,
    epgId: 'DeutscheWelle.ru',
    name: 'DW',
    type: 'tv', cat: 'news',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Deutsche_Welle_symbol_2012.svg/120px-Deutsche_Welle_symbol_2012.svg.png',
    color: '#001A80', abbr: 'DW',
  },
  {
    id: 51,
    epgId: 'AlJazeera.ru',
    name: 'Al Jazeera',
    type: 'tv', cat: 'news',
    logo: '', color: '#B71C1C', abbr: 'AJ',
  },
  {
    id: 52,
    epgId: 'CNBC.ru',
    name: 'CNBC',
    type: 'tv', cat: 'news',
    logo: '', color: '#1565C0', abbr: 'CNBC',
  },
  {
    id: 53,
    epgId: 'MTV.ru',
    name: 'MTV Russia',
    type: 'tv', cat: 'music',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/MTV_logo.svg/120px-MTV_logo.svg.png',
    color: '#000000', abbr: 'MTV',
  },
  {
    id: 54,
    epgId: 'VH1.ru',
    name: 'VH1',
    type: 'tv', cat: 'music',
    logo: '', color: '#7B1FA2', abbr: 'VH1',
  },
  {
    id: 55,
    epgId: 'Subbota.ru',
    name: 'Суббота!',
    type: 'tv', cat: 'entertainment',
    logo: '', color: '#0097A7', abbr: 'Сб!',
  },

  // ============ РАДИО ============
  {
    id: 101,
    epgId: 'RadioRossii.ru',
    name: 'Радио России',
    type: 'radio', cat: 'radio-talk',
    logo: '', color: '#1565C0', abbr: '📻',
  },
  {
    id: 102,
    epgId: 'Mayak.ru',
    name: 'Маяк',
    type: 'radio', cat: 'radio-talk',
    logo: '', color: '#C62828', abbr: '🗼',
  },
  {
    id: 103,
    epgId: 'VestiFM.ru',
    name: 'Вести FM',
    type: 'radio', cat: 'radio-news',
    logo: '', color: '#283593', abbr: '📡',
  },
  {
    id: 104,
    epgId: 'EuropaPlus.ru',
    name: 'Европа Плюс',
    type: 'radio', cat: 'radio-music',
    logo: '', color: '#E91E63', abbr: '🎶',
  },
  {
    id: 105,
    epgId: 'Avtoradio.ru',
    name: 'Авторадио',
    type: 'radio', cat: 'radio-music',
    logo: '', color: '#E53935', abbr: '🚗',
  },
  {
    id: 106,
    epgId: 'RusskoeRadio.ru',
    name: 'Русское Радио',
    type: 'radio', cat: 'radio-music',
    logo: '', color: '#F57F17', abbr: '🎵',
  },
  {
    id: 107,
    epgId: 'NasheRadio.ru',
    name: 'Наше Радио',
    type: 'radio', cat: 'radio-music',
    logo: '', color: '#2E7D32', abbr: '🎸',
  },
  {
    id: 108,
    epgId: 'LoveRadio.ru',
    name: 'Love Radio',
    type: 'radio', cat: 'radio-music',
    logo: '', color: '#E91E63', abbr: '❤',
  },
  {
    id: 109,
    epgId: 'HitFM.ru',
    name: 'HIT FM',
    type: 'radio', cat: 'radio-music',
    logo: '', color: '#BF360C', abbr: '🔥',
  },
  {
    id: 110,
    epgId: 'DFM.ru',
    name: 'DFM',
    type: 'radio', cat: 'radio-music',
    logo: '', color: '#7B1FA2', abbr: '🎧',
  },
  {
    id: 111,
    epgId: 'HumorFM.ru',
    name: 'Юмор FM',
    type: 'radio', cat: 'radio-talk',
    logo: '', color: '#F9A825', abbr: '😂',
  },
  {
    id: 112,
    epgId: 'KommersantFM.ru',
    name: 'Коммерсантъ FM',
    type: 'radio', cat: 'radio-news',
    logo: '', color: '#212121', abbr: '📰',
  },
  {
    id: 113,
    epgId: 'BusinessFM.ru',
    name: 'Business FM',
    type: 'radio', cat: 'radio-news',
    logo: '', color: '#37474F', abbr: '💼',
  },
  {
    id: 114,
    epgId: 'SportFM.ru',
    name: 'Спорт FM',
    type: 'radio', cat: 'radio-sport',
    logo: '', color: '#E65100', abbr: '🏆',
  },
  {
    id: 115,
    epgId: 'Jazz.ru',
    name: 'Jazz Radio',
    type: 'radio', cat: 'radio-music',
    logo: '', color: '#4E342E', abbr: '🎷',
  },
  {
    id: 116,
    epgId: 'RetroFM.ru',
    name: 'Ретро FM',
    type: 'radio', cat: 'radio-music',
    logo: '', color: '#6D4C41', abbr: '🎙',
  },
  {
    id: 117,
    epgId: 'RadioKlassika.ru',
    name: 'Радио Классика',
    type: 'radio', cat: 'radio-music',
    logo: '', color: '#4527A0', abbr: '🎻',
  },
  {
    id: 118,
    epgId: 'EkhoMoskvy.ru',
    name: 'Эхо Москвы',
    type: 'radio', cat: 'radio-news',
    logo: '', color: '#455A64', abbr: '🔊',
  },
  {
    id: 119,
    epgId: 'MonteCarlo.ru',
    name: 'Monte Carlo',
    type: 'radio', cat: 'radio-music',
    logo: '', color: '#00838F', abbr: '🌴',
  },
  {
    id: 120,
    epgId: 'Record.ru',
    name: 'Радио Рекорд',
    type: 'radio', cat: 'radio-music',
    logo: '', color: '#1565C0', abbr: '💿',
  },
];

// Category labels
window.CAT_LABELS = {
  federal: 'Федеральное',
  news: 'Новости',
  sport: 'Спорт',
  entertainment: 'Развлечения',
  kids: 'Детские',
  music: 'Музыкальные',
  culture: 'Культура',
  movies: 'Кино',
  doc: 'Документальные',
  'radio-talk': 'Разговорное',
  'radio-news': 'Новостное',
  'radio-music': 'Музыкальное',
  'radio-sport': 'Спортивное',
};

// Category → CSS tag class
window.CAT_TAG = {
  federal: 'tag-tv', news: 'tag-news', sport: 'tag-sport',
  entertainment: 'tag-tv', kids: 'tag-kids', music: 'tag-music',
  culture: 'tag-culture', movies: 'tag-movies', doc: 'tag-doc',
  'radio-talk': 'tag-radio', 'radio-news': 'tag-news',
  'radio-music': 'tag-music', 'radio-sport': 'tag-sport',
};
